server:
  port: 8090

spring:
  application:
    name: productinfo-api

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:productinfo;INIT=CREATE SCHEMA IF NOT EXISTS productinfo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
---
# dev, prod 등 추가
