server:
  port: 8090

spring:
  application:
    name: productinfo-api
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:productinfo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

---
# dev, prod 등 추가
